### ISSUE TITLE
Containerized pluginsync

### ISSUE THREAD

**Issue by kindermoumoute** [intelsdi-x/snap-pluginsync#56]
Pros:
- No dependency other than Docker
- Encourage contributor to run pluginsync themself
- Make automation around pluginsync simpler

I didn't find cons yet.

**Comment by nanliu** [comment]
Github authentication would be the main challenge. Maybe ssh key forwarding? Any suggestions?

**Comment by kindermoumoute** [comment]
I would think about mounting the authentification file in the container:
```bash
docker run -v ${HOME}/.netrc:/netrc intelsdi/pluginsync:0.1.11
```

**Comment by nanliu** [comment]
That works for the rake tasks, but not sure about msync where we need to git clone. We can play with this idea and see how far we get.

**Comment by nanliu** [comment]
After some investigation this is blocked by:
https://github.com/docker/for-mac/issues/410
https://github.com/docker/for-mac/issues/483

I've looked into alternatives such as https://github.com/avsm/docker-ssh-agent-forward and it is not up to date and attempts to use it results in further rabbit hole:
```
$ pinata-ssh-forward
key_load_public: invalid format
ssh_exchange_identification: read: Connection reset by peer
```

This issue is shelved until we have official socket support in docker for mac.
