### ISSUE TITLE
Bad owner or permissions on /root/.ssh/config and some ssh issues

### ISSUE THREAD

**Issue by mkleina** [intelsdi-x/snap-pluginsync#76]
Running `msync update -f <plugin_name> --noop` (actually git fetch statement running within) fails with error message containing `Bad owner or permissions on /root/.ssh/config`, for example:

```bash
root@mkleina-dev:/plugins# git '--git-dir=/plugins/modules/snap-plugin-collector-facter/.git' '--work-tree=/plugins/modules/snap-plugin-collector-facter' fetch 'origin'
Bad owner or permissions on /root/.ssh/config
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Changing access rights using `chmod 600 config` does not resolve the problem, but I found out, that running:

```
chown root /root/.ssh/config
```

from inside the container fixes bad owner error, but then new issue appears:

```bash
root@mkleina-dev:/plugins# msync update -f snap-plugin-collector-facter --noop
Syncing snap-plugin-collector-facter
Overriding any local changes to repositories in modules
2017/02/17 15:57:28 socat[141] E connect(5, AF=2 192.168.65.1:64321, 16): Connection timed out
```

I was able to fix second issue running:

```bash
eval $(ssh-agent)
ssh-add
```

Then everything works like a charm and repo is synced syccessfully. Maybe it is worth to include these commands on docker startup?

**Comment by kjlyon** [comment]
@mkleina, is this actually a bug or is it a request for better documentation in the README and on docker startup?

**Comment by mkleina** [comment]
I think it is a bug, as docker container uses user's real home folder as /root volume and do not set owner privileges for SSH config file. Also user's SSH private key for GitHub access is not added, so it is impossible to use git command inside docker container, which is needed for pluginsync to work.

**Comment by mkleina** [comment]
@kjlyon I think it is a bug, as docker container uses user's real home folder as /root volume and do not set owner privileges for SSH config file. Also user's SSH private key for GitHub access is not added, so it is impossible to use git command inside docker container, which is needed for pluginsync to work.

**Comment by mkleina** [comment]
@kjlyon I think it is a bug, as docker container uses host's user home folder as /root volume and do not set owner privileges for SSH config file. Also user's SSH private key for GitHub access is not added, so it is impossible to use git command inside docker container, which is needed for pluginsync to work.

**Comment by nanliu** [comment]
@mkleina, are you using windows, mac, or linux? I'm not sure this works for Windows systems, but should behave correctly for linux/mac.

The script relies on your system's ssh-agent socket getting forwarded to the docker-container, and does not expect keys to exist in the container. Also it should mount your user home directory over the /root/.ssh/ folder (since we specify `docker run -v "${HOME}":/root ...`), so the content in the container should not matter.

Before you run pluginsync.sh make sure you have ssh-agent running on your system. When you execute pluginsync.sh the script will forward $SSH_AUTH_SOCK via socat and mount it in the container as /var/run/ssh_agent.sock:
```
$ ssh-add -l
2048 SHA256:aGzYyKujPoTW8ZHzUm5vuzQbsbzGgSe7JrkXkGr9fl8 /Users/nanliu/.ssh/intel.rsa (RSA)
$ echo $SSH_AUTH_SOCK
/var/folders/1n/qv6ftkx5269gxv31615phkfc0000gp/T//ssh-SisyDI1Oaxek/agent.861
$ ./pluginsync.sh
commands do not be prefixed with bundle exec, try: "rake -T" or "travis" or "msync"
root@18411c89187b:/plugins# echo $SSH_AUTH_SOCK
/var/run/ssh_agent.sock
root@18411c89187b:/plugins# ssh-add -l
2048 65:50:56:62:39:ad:2b:db:1b:0c:f1:47:0a:e9:6e:54 /Users/nanliu/.ssh/intel.rsa (RSA)
```

If you install the file package, you should be able to verify this is indeed a socket in the container:
```
root@18411c89187b:/plugins# apt update
root@18411c89187b:/plugins# apt install file
root@18411c89187b:/plugins# file $SSH_AUTH_SOCK
/var/run/ssh_agent.sock: socket
```

Ping me on slack if you want to do a quick remote troubleshooting session.

**Comment by mkleina** [comment]
@nanliu I am using Linux, Ubuntu 16.04. Just cloned pluginsync repo minute ago and tried to repeat your steps.

In my terminal:
```bash
mkleina@mkleina-dev:~/snap-pluginsync$ ssh-add -l
2048 SHA256:mpfxtuziGtLEqqsDYRu7q22FxIPNxFcKiWnQcr9aerA mkleina@mkleina-dev (RSA)
mkleina@mkleina-dev:~/snap-pluginsync$ echo $SSH_AUTH_SOCK
/run/user/1000/keyring/ssh
```

In docker container:
```
commands do not be prefixed with bundle exec, try: "rake -T" or "travis" or "msync"
root@mkleina-dev:/plugins# ssh-add -l
2017/03/06 10:41:51 socat[75] E connect(5, AF=2 192.168.65.1:64321, 16): Connection timed out
Error reading response length from authentication socket.
root@mkleina-dev:/plugins# echo $SSH_AUTH_SOCK
/var/run/ssh_agent.sock
root@mkleina-dev:/plugins# file $SSH_AUTH_SOCK
/var/run/ssh_agent.sock: socket
```

Maybe it is something wrong with my setup, but as normal user I am not able to use this tool without my workarounds for this moment.

**Comment by nanliu** [comment]
@mkleina, docker-for-mac the mac host ipaddress reachable by the containers is 192.168.65.1. How this ipaddress is configured is honestly a bit of mystery, since it does not show up in the host network, or docker network. but it can be verified by checking the dhcp setting:

```
$ ./pluginsync.sh
commands do not be prefixed with bundle exec, try: "rake -T" or "travis" or "msync"
root@moby:/plugins# cat /etc/resolv.conf
# Generated by dhcpcd from eth0.dhcp
# /etc/resolv.conf.head can replace this line
nameserver 192.168.65.1
```

Can you run `./pluginsync.sh`, and let me know what's the ipaddress shown in the container's /etc/resolv.conf? If it's also 192.168.65.1, then it's most likely host based firewall (iptables) that's blocking access to the ssh socket forwarded by socat.

**Comment by mkleina** [comment]
@mkeina Sure, this is my `/etc/resolv.conf` inside docker container:

```bash
root@mkleina-dev:/plugins# cat /etc/resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 127.0.1.1
search igk.intel.com
```

**Comment by nanliu** [comment]
@mkleina, ok please change 192.68.65.1 to 127.0.1.1 in the following line:
https://github.com/intelsdi-x/snap-pluginsync/blob/master/pluginsync.sh#L31

Start `./pluginsync.sh` and run `ssh-add -l` in the container again. I'm still not sure how we determine this IP, but hoping this will fix your issue.

**Comment by mkleina** [comment]
@nanliu After changing to 127.0.0.1 it works now! So this line should be fixed, thank you!

**Comment by nanliu** [comment]
@mkleina, that works for your system, we need a way to detect the difference between docker configs. I'm not sure how to do that yet, so open to suggestions.
